name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main

permissions:
  checks: write
  contents: read
  deployments: write
  pull-requests: write
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_SERVICE_ACCOUNT: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MACHUB_6AF39 }}'
        run: |
          echo "$FIREBASE_SERVICE_ACCOUNT" > service-account-temp.json
          export GOOGLE_APPLICATION_CREDENTIALS=service-account-temp.json
          npx firebase-tools deploy --only hosting --project machub-6af39
          rm service-account-temp.json
